---
- hosts: all

  tasks:
    - name: Create zabbix directory if it does not exist.
      become: yes
      file:
        path: /var/run/zabbix
        state: directory
        owner: zabbix
        group: zabbix
      register: directory_created
    - name: Restart zabbix service if directory is created.
      become: yes
      service:
        name: zabbix-agent.service
        state: restarted
      when: directory_created.changed
